### ISSUE TITLE
ai2html sets a max_width of 460 even when biggest artboard is 335

### ISSUE THREAD

**Issue by giratikanon** [newsdev/ai2html#125] opened 2019-09-13 15:12 UTC
![image](https://user-images.githubusercontent.com/333527/64873544-4d3dd300-d617-11e9-9c4f-dfebb6ccdd14.png)

Sample AI file: https://preview.nyt.net/cgit/cgit.cgi/nytg/2019-09-12-golzow-dispatch-map.git/tree/ai?id=211d92504bc5536e731bee9f70a61138ffd08821

**Comment by mbloch** [comment] 2019-09-13 15:33
I can't reproduce the issue with the current version of ai2html (0.94.1). Does the problem still occur after upgrading?

**Comment by mbloch** [comment] 2019-09-13 15:43
I confirmed that this bug has been fixed since v0.89.0... closing

**Closed by mbloch** 2019-09-13 15:43 UTC
