### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by robmoggach** [newsdev/ai2html#27] opened 2016-01-22 17:28 UTC
type object that is rotated and has a layer style applied (drop shadow) is within a group with a css property defined - 

doesn't happen with `render_rotated_skewed_text_as: image` is set.

![screenshot 2016-01-22 12 20 42](https://cloud.githubusercontent.com/assets/184759/12517976/ae5bff36-c103-11e5-8345-255adcf42efc.jpg)

**Comment by robmoggach** [comment] 2016-01-22 17:59
this is sometimes related to the `ai2html-settings` text block?
after the script runs it's often selected and quite easy to accidentally edit... I've added a space before the first line a few times now... 

* maybe the script can deselect it before and after the script runs? 
* maybe it's identified by an attribute instead of it's first line which is prone to user error... parse the info and throw out anything that isn't a preference... an attribute is more likely to not be accidentally deleted
* while we're at it... how about a mono spaced font for kicks... courier, monaco, etc.

**Comment by robmoggach** [comment] 2016-01-22 18:38
hmmm... also getting this with single text object with glow and a rotation inside a group with itself as the only object within the group... take it out of the group and i don't get this error

**Comment by mbloch** [comment] 2017-04-06 02:07
I was able to reproduce this error in the current release version (v0.63). The problem is fixed in the current ai2html-beta.js, which will be released as v0.64 soon.

**Closed by mbloch** 2017-04-06 02:07 UTC
